# See https://docs.travis-ci.com/user/reference/overview/
dist: bionic

language: java

jdk:
  - openjdk16
  - openjdk15
  - openjdk11
  - openjdk8

env:
  global:
    # GITHUB_TOKEN value to push changes to GitHub; Currently it is used to update gh-pages.
    - secure: "KqPuq9TiiqdOUfGq3k+XYObNjV8FxbgJeqSWK0pcWFFs5w5c4vcGmrfUSSSqNa/JJkKOBWQ6S3tJP7CRxx0uow5BvU4ZQAZLFt6VjzcUZFKGTl5soMTF2gQdyAAcwUnRX2gQKt0doO8Fid6xzfsn1KdTIWXmeqMrcTvC+d7EhxU="

script:
  - ./mvnw verify -B -P run-its -DtestSrc=remote -Dinvoker.parallelThreads=4

deploy:
  - provider: script
    skip_cleanup: true
    script: ./mvnw site -B -Ddownloader.tls.protocols=TLSv1.2,TLSv1.3
    email: jeremylandis@hotmail.com
    on:
      repo: spotbugs/spotbugs-maven-plugin
      branch: spotbugs
      jdk: openjdk11
      condition: $TRAVIS_COMMIT_MESSAGE !~ ^\[maven-release-plugin\]*

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: target/site
    email: skypencil+spotbugs-bot@gmail.com
    on:
      repo: spotbugs/spotbugs-maven-plugin
      branch: spotbugs
      jdk: openjdk11
      condition: $TRAVIS_COMMIT_MESSAGE !~ ^\[maven-release-plugin\]*
